# Upload a Python Package using Twine when a semver tag is pushed to
# the default branch
#
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Publish to PyPI

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  publish-package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ matrix.os }}-poetry-${{ hashFiles('poetry.lock') }}
        restore-keys: |
          ${{ matrix.os }}-poetry-

    - name: Install pip and poetry
      run: |
        python -m pip install --upgrade pip
        pip install --user poetry

    - name: Install package with its dependencies
      run: |
        ~/.local/bin/poetry install

    - name: Build package
      run: |
        ~/.local/bin/poetry build

    - name: Publish package to PyPI
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_PASSWORD }}
      run: |
        ~/.local/bin/poetry publish
